# This is a basic workflow to help you get started with Actions

name: import pdf

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: download pdf
        shell: bash
        run: "wget 'https://docs.google.com/document/d/11CDHkZ-oSTM62-riHNhNQUNxES3YDt5_uADfA9piqLw/export?format=pdf' -O tmp.pdf"
      - name: replace pdf with newer
        shell: bash
        run: "mv tmp.pdf haainfo.pdf"
      - name: commit new pdf
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update pdf"
          git push
